language: ko

reviews:
  profile: chill
  high_level_summary: true
  sequence_diagrams: false
  poem: false
  auto_review:
    enabled: true
    drafts: false
  path_filters:
    - "!**/build/**"
    - "!**/.gradle/**"
