spring:
  profiles.active: local

  jpa:
    open-in-view: false

secret:
  jwt:
    secret-key: ${JWT_SECRET_KEY}
    expire-time: ${JWT_EXPIRE_TIME}

oauth:
  apple:
    key: ${APPLE_KEY_ID}
    team-id: ${APPLE_TEAM_ID}
    client-id: ${APPLE_CLIENT_ID}
    private-key: ${APPLE_PRIVATE_KEY}
