spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:33306/dogether
    username: root
    password: root

  jpa:
    hibernate.ddl-auto: create

logging:
  config: classpath:logback/logback-local.xml
  level:
    root: info
    site.dogether: trace

decorator:
  datasource:
    p6spy:
      enable-logging: true
